### ISSUE TITLE
Project Setup: Exception at initialize-admin

### ISSUE THREAD

**Issue by n0rwin** [jamesej/lyniconanc#8]
I tried setting up a completely new project following the guide at [lynicon.atlassian.net](https://lynicon.atlassian.net/wiki/spaces/LAC/pages/363495425/Installing+to+a+New+Project+-+VS2017+.Net+4.6.1+.Net+Standard+2.0+Core+2.1)

Target framework: .NET Core 2.1
LyniconANC 0.2.2.24
Microsoft.AspNetCore.App 2.1.1
Database: SQL Server 14.0.2002.14

I used `dotnet run -- --lynicon initialize-database`
From what I can tell the database is set up fine. I see 3 tables (ContentItems, DbChanges, Users) in my database.

Then i use `dotnet run -- --lynicon initialize-admin --password <redacted>` which gives me the following error.

`C:\projects\tryouts\LyniconTest\LyniconTest>dotnet run -- --lynicon initialize-admin --password <redacted>
Die Starteinstellungen von C:\projects\tryouts\LyniconTest\LyniconTest\Properties\launchSettings.json werden verwendet.
info: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[0]
      User profile is available. Using 'C:\Users\norbert.winkler\AppData\Local\ASP.NET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at rest.
Application startup exception: System.ArgumentNullException: Value cannot be null.
Parameter name: relationalTypeMapping
   at Microsoft.EntityFrameworkCore.Utilities.Check.NotNull[T](T value, String parameterName)
   at Microsoft.EntityFrameworkCore.Storage.Internal.TypeMappedRelationalParameter..ctor(String invariantName, String name, RelationalTypeMapping relationalTypeMapping, Nullable`1 nullable)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalParameterBuilder.AddParameter(String invariantName, String name, IProperty property)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommandBuilderExtensions.AddParameter(IRelationalCommandBuilder commandBuilder, String invariantName, String name, IProperty property)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.CreateStoreCommand()
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(DbContext _, ValueTuple`2 parameters)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IReadOnlyList`1 entries)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges()
   at Lynicon.DataSources.CoreDataSource.SaveChanges()
   at Lynicon.Repositories.BasicRepository.Set(List`1 items, Dictionary`2 setOptions)
   at Lynicon.Repositories.Repository.<>c__DisplayClass48_0.<Set>b__1(IGrouping`2 igroup)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.ToList()
   at Lynicon.Repositories.Repository.Set(List`1 items, Dictionary`2 setOptions)
   at Lynicon.Collation.BasicCollator.Set(Address a, Object data, Dictionary`2 setOptions)
   at Lynicon.Collation.Collator.Set(Address address, Object data, Dictionary`2 setOptions)
   at Lynicon.Collation.Collator.Set(Address address, Object data, Nullable`1 create, Boolean bypassChecks)
   at Lynicon.Collation.Collator.Set(Address address, Object data, Nullable`1 create)
   at Lynicon.Collation.Collator.Set(Object data, Nullable`1 create)
   at Lynicon.Membership.SecurityManager.EnsureAdminUser(String password)
   at Lynicon.Commands.InitializeAdminCmd.Execute(String[] args)
   at Lynicon.Commands.CommandRunner.<>c__DisplayClass8_0.<GetCommand>b__1()
   at Lynicon.Commands.CommandRunner.InterceptAndRunCommands(String[] args)
   at Lynicon.Commands.CommandRunner.InterceptAndRunCommands(IServiceProvider services, String[] args)
   at Lynicon.Commands.CommandRunner.InterceptRunStartupFilter.<>c__DisplayClass2_0.<Configure>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.AutoRequestServicesStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
crit: Microsoft.AspNetCore.Hosting.Internal.WebHost[6]
      Application startup exception
System.ArgumentNullException: Value cannot be null.
Parameter name: relationalTypeMapping
   at Microsoft.EntityFrameworkCore.Utilities.Check.NotNull[T](T value, String parameterName)
   at Microsoft.EntityFrameworkCore.Storage.Internal.TypeMappedRelationalParameter..ctor(String invariantName, String name, RelationalTypeMapping relationalTypeMapping, Nullable`1 nullable)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalParameterBuilder.AddParameter(String invariantName, String name, IProperty property)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommandBuilderExtensions.AddParameter(IRelationalCommandBuilder commandBuilder, String invariantName, String name, IProperty property)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.CreateStoreCommand()
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(DbContext _, ValueTuple`2 parameters)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IReadOnlyList`1 entries)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges()
   at Lynicon.DataSources.CoreDataSource.SaveChanges()
   at Lynicon.Repositories.BasicRepository.Set(List`1 items, Dictionary`2 setOptions)
   at Lynicon.Repositories.Repository.<>c__DisplayClass48_0.<Set>b__1(IGrouping`2 igroup)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.ToList()
   at Lynicon.Repositories.Repository.Set(List`1 items, Dictionary`2 setOptions)
   at Lynicon.Collation.BasicCollator.Set(Address a, Object data, Dictionary`2 setOptions)
   at Lynicon.Collation.Collator.Set(Address address, Object data, Dictionary`2 setOptions)
   at Lynicon.Collation.Collator.Set(Address address, Object data, Nullable`1 create, Boolean bypassChecks)
   at Lynicon.Collation.Collator.Set(Address address, Object data, Nullable`1 create)
   at Lynicon.Collation.Collator.Set(Object data, Nullable`1 create)
   at Lynicon.Membership.SecurityManager.EnsureAdminUser(String password)
   at Lynicon.Commands.InitializeAdminCmd.Execute(String[] args)
   at Lynicon.Commands.CommandRunner.<>c__DisplayClass8_0.<GetCommand>b__1()
   at Lynicon.Commands.CommandRunner.InterceptAndRunCommands(String[] args)
   at Lynicon.Commands.CommandRunner.InterceptAndRunCommands(IServiceProvider services, String[] args)
   at Lynicon.Commands.CommandRunner.InterceptRunStartupFilter.<>c__DisplayClass2_0.<Configure>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.AutoRequestServicesStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()

Unhandled Exception: System.ArgumentNullException: Value cannot be null.
Parameter name: relationalTypeMapping
   at Microsoft.EntityFrameworkCore.Utilities.Check.NotNull[T](T value, String parameterName)
   at Microsoft.EntityFrameworkCore.Storage.Internal.TypeMappedRelationalParameter..ctor(String invariantName, String name, RelationalTypeMapping relationalTypeMapping, Nullable`1 nullable)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalParameterBuilder.AddParameter(String invariantName, String name, IProperty property)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommandBuilderExtensions.AddParameter(IRelationalCommandBuilder commandBuilder, String invariantName, String name, IProperty property)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.CreateStoreCommand()
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(DbContext _, ValueTuple`2 parameters)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IReadOnlyList`1 entries)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges()
   at Lynicon.DataSources.CoreDataSource.SaveChanges()
   at Lynicon.Repositories.BasicRepository.Set(List`1 items, Dictionary`2 setOptions)
   at Lynicon.Repositories.Repository.<>c__DisplayClass48_0.<Set>b__1(IGrouping`2 igroup)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.ToList()
   at Lynicon.Repositories.Repository.Set(List`1 items, Dictionary`2 setOptions)
   at Lynicon.Collation.BasicCollator.Set(Address a, Object data, Dictionary`2 setOptions)
   at Lynicon.Collation.Collator.Set(Address address, Object data, Dictionary`2 setOptions)
   at Lynicon.Collation.Collator.Set(Address address, Object data, Nullable`1 create, Boolean bypassChecks)
   at Lynicon.Collation.Collator.Set(Address address, Object data, Nullable`1 create)
   at Lynicon.Collation.Collator.Set(Object data, Nullable`1 create)
   at Lynicon.Membership.SecurityManager.EnsureAdminUser(String password)
   at Lynicon.Commands.InitializeAdminCmd.Execute(String[] args)
   at Lynicon.Commands.CommandRunner.<>c__DisplayClass8_0.<GetCommand>b__1()
   at Lynicon.Commands.CommandRunner.InterceptAndRunCommands(String[] args)
   at Lynicon.Commands.CommandRunner.InterceptAndRunCommands(IServiceProvider services, String[] args)
   at Lynicon.Commands.CommandRunner.InterceptRunStartupFilter.<>c__DisplayClass2_0.<Configure>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.AutoRequestServicesStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.StartAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String shutdownMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)
   at LyniconTest.Program.Main(String[] args) in C:\projects\tryouts\LyniconTest\LyniconTest\Program.cs:line 20`

The admin user isn't created. I cannot login going to /lynicon/login. It gives me the message "The user name or password provided is incorrect".
The Users table in the database is also empty.

**Comment by jamesej** [comment]
Thanks for reporting this, we will investigate immediately.

**Comment by n0rwin** [comment]
Awesome, thank you
